rebrandly_poc:
  outputs:
    dev:
      type: duckdb
      path: dev.duckdb
      threads: 1
      extensions:
        - httpfs
        - parquet
      settings:
        s3_region: "{{ env_var('AWS_REGION') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"

    prod:
      type: duckdb
      path: prod.duckdb
      threads: 4

  target: dev
